### ISSUE TITLE
user_ctl_mizuRoute file doesn't work for some settings

### ISSUE THREAD

**Issue by ekluzek** [NCAR/mizuRoute#152]
The user_ctl_mizuRoute override for a specific case isn't working to control some settings (like changing filenames). It works for other settings (like route_opt). user_nl_mizuRoute seems to work fine.

**Comment by ekluzek** [comment]
It looks like the reason is that the user_ctl_mizuRoute file is read first, but then custom settings are done that override whatever was set before (from either the base file used or the user_ctl file). This can be done that way for the user_nl_mizuRoute file, because the namelist won't override settings that are already set. But, the mizuRoute control settings do get overridden. So the user_ctl_mizuRoute file just needs to be read after everything else is set. So this is a pretty straightforward change needed.

**Comment by nmizukami** [comment]
Fixed at PR #156
