### ISSUE TITLE
Connect PIO xml settings

### ISSUE THREAD

**Issue by ekluzek** [NCAR/mizuRoute#186]
Currently the cesm-coupling branch has the PIO settings hardcoded in, and doesn't respond to the XML ROF PIO settings. This needs to change so that it responds to the XML settings. @jedwards4b pointed this out in issue #184

**Comment by nmizukami** [comment]
Hi Erik @ekluzek,  actually this case statement overwrite `pio_netcdf_format` mizuRoute global variable and change netcdf format.` shr_pio_getioformat(inst_name)` is from xml pio settings.  I tested this and verified that output netcdf format changed.

https://github.com/NCAR/mizuRoute/blob/e99eb61a06e4f887510722e5ae1f961f6bd82a4c/route/build/cpl/RtmMod.F90#L127-L131

**Comment by nmizukami** [comment]
Looks like i can close this one.
