### ISSUE TITLE
SourceMods functionality issue

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/mizuRoute#188]
As written buildlib for mizuRoute does not find a file added to SourceMods/src.mizuroute unless
1. The code has not been built prior to adding the file or
2. The file bld/rof/obj/Filepath is removed.

**Comment by ekluzek** [comment]
OK, looking into this it looks like the same problem would apply to: CTSM, cism, mosart, and RTM. The csm_share buildlib is slightly different in that if the number of lines of the file changes it will update it. But, I actually don't expect that will actually happen, so I'm not thinking that needs to be done. Is there another example of a buildlib with Filepath that works differently? Or is there something else in how the SourceMods are handled? I found buildlib for other libraries that work differently, but these were ones that were using CMAKE or only had a single directory so I didn't think they applied.

In this situation when adding a new file I expect that I need to rerun the dependence generator. So I expect to have to do this...

./case.build --clean-depends rof

I think that should function the same as removing the Filepath file. But, it's also something that I've expected to have to do when adding new files.

**Comment by jedwards4b** [comment]
Sorry - I misinterpreted the problem.  I'll close this issue.
