### ISSUE TITLE
Mismatch between hru and hruId

### ISSUE THREAD

**Issue by msaharia** [NCAR/mizuRoute#23]
When the dimension name is `hru` with serial indices and `hruId` is a variable with HRU indices, routing stops with this error:
```

 Route all the segments included in network topology
 maximum upstream area =    660573269331.323             4506
 FATAL ERROR: get_qDims/NetCDF: Invalid dimension ID or name; name=hruId
```

**Comment by nmizukami** [comment]
This is fixed in branch called `https://github.com/nmizukami/mizuRoute/tree/feature/runoff_remap` for the latest code that is working.
